stages:
  data_ingestion:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_03_training.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_03_training.py
      - config/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/Chicken-fecal-images
      - src/ChickenDiseaseClassification/components/prepare_callbacks.py
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.keras

  evaluation:
    cmd: python src/ChickenDiseaseClassification/pipeline/stage_04_evaluation.py
    deps:
      - src/ChickenDiseaseClassification/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/training/model.keras
      - artifacts/data_ingestion/Chicken-fecal-images
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false


